apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: db
  namespace: zabbix
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-server
  externalIPs:
  - <Specify external IP here>
  type: NodePort
  selector:
    name: mysql-server
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zabbix-db-storage
  labels:
    type: local
  namespace: zabbix
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/zabbix_db_storage"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-db-storage-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: zabbix-db-storage
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: mysql-server
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
        app: zabbix
        tier: mysql-server
    spec:
      containers:
        - name: zabbix-db
          image: mysql:8.0
          command: ["--character-set-server=utf8 --collation-server=utf8_bin"]
          ports:
          - containerPort: 3306
            name: mysql
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
           - mountPath: "/var/lib/mysql/"
             name: zabbix-db-storage
             readOnly: false
      volumes:
       - name: zabbix-db-storage
         persistentVolumeClaim:
          claimName: zabbix-db-storage-claim