apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: db
  namespace: zabbix
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-server
  externalIPs:
  - <Specify external IP here>
  type: NodePort
  selector:
    name: mysql-server
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zabbix-db-storage
  labels:
    type: local
  namespace: zabbix
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/zabbix_db_storage"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-db-storage-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: zabbix-db-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql-server
  namespace: zabbix
data:
  my.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8mb4
    password="zabbix"

    [mysql]
    default-character-set=utf8mb4

    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0

    [mysqld]
    user   = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    port   = 3306
    basedir    = /usr
    datadir    = /var/lib/mysql
    tmpdir   = /tmp
    lc-messages-dir  = /usr/share/mysql-8.0
    lc-messages  = en_US
    explicit_defaults_for_timestamp
    collation-server = utf8mb4_unicode_520_ci
    init-connect='SET NAMES utf8mb4'
    character-set-server = utf8mb4
    #log-error  = /var/log/mysql/error.log
    # Recommended in standard MySQL setup
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    # Disabling symbolic-links is recommended to prevent assorted security risks
    #symbolic-links=0
    # This increase of max_connections from the default of 151 to 1024 has been
    # tested as adequate for an environment with up to 24 API/Worker/Collector
    # components (8 of each) and 4000 Agents of incoming traffic. The MySQL
    # container also consumed as much as 1 GB of memory in this test.
    max_connections=1024
    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: mysql-server
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
        app: zabbix
        tier: mysql-server
    spec:
      containers:
        - name: zabbix-db
          image: mysql:8.0
          ports:
          - containerPort: 3306
            name: mysql
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
           - mountPath: "/var/lib/mysql/"
             name: zabbix-db-storage
             readOnly: false
           - mountPath: "/etc/mysql/my.cnf"
             name: mysql-config
             subPath: my.cnf
      volumes:
       - name: zabbix-db-storage
         persistentVolumeClaim:
          claimName: zabbix-db-storage-claim
       - name: mysql-config
         configMap:
            name: mysql-config