apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web-http
  - port: 443
    targetPort: 8443
    name: web-https
  externalIPs:
  - <Specify external IP here>
  selector:
    name: zabbix-web
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: zabbix-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: zabbix-web
  namespace: zabbix
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-5.2-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web-http
          - containerPort: 8443
            name: web-https
          resources:
           limits:
            cpu: 200m
            memory: 400Mi
           requests:
            cpu: 200m
            memory: 400Mi
          livenessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          env:
          - name: ZBX_SERVER_HOST
            value: "<Specify ZX external IP here>"
          - name: ZBX_SERVER_PORT
            value: "Zabbix kubernetes"
          - name: ZBX_SERVER_NAME
            value: "Zabbix kubernetes"
          - name: PHP_TZ
            value: "Africa/Casablanca"
          - name: DB_SERVER_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: DB_SERVER_PASS
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: DB_SERVER_HOST
            value: "<Specify DB external IP here>"
          - name: DB_SERVER_PORT
            value: "<Specify DB external PORT here>"
          - name: DB_SERVER_DBNAME
            value: "zabbix"
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
          - name: zabbix-web-ssl
            mountPath: /etc/ssl/nginx
            readOnly: true
      volumes:
       - hostPath:
          path: /home/dotneft/zbx/zbx_env/etc/ssl/nginx/
         name: zabbix-web-ssl