apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: mysql-server
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
        app: zabbix
        tier: mysql-server
    spec:
      volumes:
       - name: zabbix-mysql-data
         persistentVolumeClaim:
          claimName: zabbix-mysql-data-claim
      containers:
        - name: zabbix-db
          image: mysql:5.7
          ports:
          - containerPort: 3306
            name: mysql
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
           - mountPath: "/var/lib/mysql/"
             name: zabbix-mysql-data
             readOnly: false