apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-claim
  namespace: grafana
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: grafana-storage