apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
        app: grafana
    spec: 
      containers:
        - name: grafana
          image: monitoringartist/grafana-xxl
          ports:
            - containerPort: 3000
              name: http-grafana
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
              readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-grafana-storage-claim