apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
        app: grafana
    spec: 
      containers:
        - name: grafana
          image: monitoringartist/grafana-xxl
          command: ["sed"]
          args: ['-i -e "s/;allow_embedding = false/allow_embedding = true/" /etc/grafana/grafana.ini']
           # sed -i -e "s/;allow_embedding = false/allow_embedding = true/" /etc/grafana/grafana.ini
           # sed -i -e "s/;enabled = false/enabled = false/" /etc/grafana/grafana.ini
           # sed -i -e "s/;org_name = Main Org./org_name = Main Org./" /etc/grafana/grafana.ini
          ports:
            - containerPort: 3000
              name: http-grafana
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
              readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage-claim