apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    name: grafana-http
  type: NodePort
  externalIPs:
  - <Specify external IP here>
  selector:
    name: grafana