kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-data
  labels:
    type: local
  namespace: grafana
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/grafana_data"