apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0    
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http-grafana
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
              readOnly: false
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc