apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  externalIPs:
  -  <Specify external IP here>
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort