apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-server
  labels:
    app: zabbix
    tier: postgres-server
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-server
        app: zabbix
        tier: postgres-server
    spec:
      volumes:
       - name: zabbix-db-storage
         persistentVolumeClaim:
          claimName: zabbix-db-storage-claim
      containers:
        - name: zabbix-db
          image: postgres:latest
          ports:
          - containerPort: 5432
            name: postgres
          env:
          - name: POSTGRES_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: POSTGRES_DB
            value: "zabbix"
          volumeMounts:
           - mountPath: "/var/lib/postgres/"
             name: zabbix-db-storage
             readOnly: false