apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
    environment: dev
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:centos-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          env:
          - name: DB_SERVER_HOST  
            value: "<Specify DB external IP here>"
          - name: POSTGRES_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: POSTGRES_DB
            value: "zabbix"
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_STARTPROXYPOLLERS
            value: "5"
          - name: ZBX_PROXYCONFIGFREQUENCY
            value: "60"
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: true
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 1162
            protocol: UDP
            name: snmp-trap
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: false
      volumes:
       - hostPath:
          path: /zabbix/
         name: zabbix-db-storage