apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10050
    targetPort: 10050
    name: zabbix-agent
  externalIPs:
  - <Specify external IP here>
  selector:
    name: zabbix-agent