apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-proxy-postgres
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-proxy-postgres
        app: zabbix
    spec:
      containers:
        - name: zabbix-proxy-postgres
          image: zabbix/zabbix-proxy-postgres:alpine-5.4-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          env:
          - name: POSTGRES_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: POSTGRES_DB
            value: "zabbix_proxy"