kind: PersistentVolume
apiVersion: v1
metadata:
  name: zabbix-db-storage
  labels:
    type: local
  namespace: zabbix
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/zabbix_db_storage"