kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-db-storage-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: zabbix-db-storage