kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-db-data-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: zabbix-db-data