kind: PersistentVolume
apiVersion: v1
metadata:
  name: zabbix-db-data
  labels:
    type: local
  namespace: zabbix
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"